<?php

$prefix = "achievement";

$statList = array
(
    "acquireIron" => array("L'âge du fer", ""),
    "bakeCake" => array("La cerise sur le gâteau", ""),
    "blazeRod" => array("Dans le feu de l'action", ""),
    "bookcase" => array("Rat de bibliothèque", ""),
    "breedCow" => array("Repeuplement", ""),
    "buildBetterPickaxe" => array("Qualité supérieure !", ""),
    "buildFurnace" => array("Au fourneau !", ""),
    "buildHoe" => array("Il est temps de cultiver", ""),
    "buildPickaxe" => array("Bonne pioche !", ""),
    "buildSword" => array("À l'attaque !", ""),
    "buildWorkBench" => array("Au travail !", ""),
    "cookFish" => array("Un délicieux poisson", ""),
    "diamonds" => array("DES DIAMANTS !", ""),
    "diamondsToYou" => array("Des diamants pour vous !", ""),
    "enchantments" => array("Enchanté", ""),
    "exploreAllBiomes" => array("Partons à l’aventure !", ""),
    "flyPig" => array("Aéro-porc", ""),
    "fullBeacon" => array("Phare à on", ""),
    "ghast" => array("Retour à l'envoyeur", ""),
    "killCow" => array("Tanneur en devenir", ""),
    "killEnemy" => array("Chasseur de monstres", ""),
    "killWither" => array("Le commencement.", ""),
    "makeBread" => array("Du pain sur la planche", ""),
    "mineWood" => array("Coupons du bois !", ""),
    "onARail" => array("Sur la bonne voie", ""),
    "openInventory" => array("Faire l’inventaire", ""),
    "overkill" => array("Massacre", ""),
    "overpowered" => array("Surpuissant", ""),
    "portal" => array("Aller au fond des choses", ""),
    "potion" => array("Apprenti chimiste", ""),
    "snipeSkeleton" => array("Duel de snipers", ""),
    "spawnWither" => array("Le commencement ?", ""),
    "theEnd" => array("Fin?", ""),
    "theEnd2" => array("Fin.", ""),
);

?>