<?php

$statList = array
(
    "breakItem.minecraft.bow" => array("Bow", ""),
    "breakItem.minecraft.carrot_on_a_stick" => array("Carrot on a stick", ""),
    "breakItem.minecraft.chainmail_boots" => array("Chainmail boots", ""),
    "breakItem.minecraft.chainmail_chestplate" => array("Chainmail chestplate", ""),
    "breakItem.minecraft.chainmail_helmet" => array("Chainmail helmet", ""),
    "breakItem.minecraft.chainmail_leggings" => array("Chainmail leggings", ""),
    "breakItem.minecraft.diamond_axe" => array("Diamond axe", ""),
    "breakItem.minecraft.diamond_boots" => array("Diamond boots", ""),
    "breakItem.minecraft.diamond_chestplate" => array("Diamond chestplate", ""),
    "breakItem.minecraft.diamond_helmet" => array("Diamond helmet", ""),
    "breakItem.minecraft.diamond_hoe" => array("Diamond hoe", ""),
    "breakItem.minecraft.diamond_leggings" => array("Diamond leggings", ""),
    "breakItem.minecraft.diamond_pickaxe" => array("Diamond pickaxe", ""),
    "breakItem.minecraft.diamond_shovel" => array("Diamond shovel", ""),
    "breakItem.minecraft.diamond_sword" => array("Diamond sword", ""),
    "breakItem.minecraft.fishing_rod" => array("Fishing rod", ""),
    "breakItem.minecraft.flint_and_steel" => array("Flint and steel", ""),
    "breakItem.minecraft.golden_axe" => array("Golden axe", ""),
    "breakItem.minecraft.golden_boots" => array("Golden boots", ""),
    "breakItem.minecraft.golden_chestplate" => array("Golden chestplate", ""),
    "breakItem.minecraft.golden_helmet" => array("Golden helmet", ""),
    "breakItem.minecraft.golden_hoe" => array("Golden hoe", ""),
    "breakItem.minecraft.golden_leggings" => array("Golden leggings", ""),
    "breakItem.minecraft.golden_pickaxe" => array("Golden pickaxe", ""),
    "breakItem.minecraft.golden_shovel" => array("Golden shovel", ""),
    "breakItem.minecraft.golden_sword" => array("Golden sword", ""),
    "breakItem.minecraft.iron_axe" => array("Iron axe", ""),
    "breakItem.minecraft.iron_boots" => array("Iron boots", ""),
    "breakItem.minecraft.iron_chestplate" => array("Iron chestplate", ""),
    "breakItem.minecraft.iron_helmet" => array("Iron helmet", ""),
    "breakItem.minecraft.iron_hoe" => array("Iron hoe", ""),
    "breakItem.minecraft.iron_leggings" => array("Iron leggings", ""),
    "breakItem.minecraft.iron_pickaxe" => array("Iron pickaxe", ""),
    "breakItem.minecraft.iron_shovel" => array("Iron shovel", ""),
    "breakItem.minecraft.iron_sword" => array("Iron sword", ""),
    "breakItem.minecraft.leather_boots" => array("Leather boots", ""),
    "breakItem.minecraft.leather_chestplate" => array("Leather chestplate", ""),
    "breakItem.minecraft.leather_helmet" => array("Leather helmet", ""),
    "breakItem.minecraft.leather_leggings" => array("Leather leggings", ""),
    "breakItem.minecraft.shears" => array("Shears", ""),
    "breakItem.minecraft.stone_axe" => array("Stone axe", ""),
    "breakItem.minecraft.stone_hoe" => array("Stone hoe", ""),
    "breakItem.minecraft.stone_pickaxe" => array("Stone pickaxe", ""),
    "breakItem.minecraft.stone_shovel" => array("Stone shovel", ""),
    "breakItem.minecraft.stone_sword" => array("Stone sword", ""),
    "breakItem.minecraft.wooden_axe" => array("Wooden axe", ""),
    "breakItem.minecraft.wooden_hoe" => array("Wooden hoe", ""),
    "breakItem.minecraft.wooden_pickaxe" => array("Wooden pickaxe", ""),
    "breakItem.minecraft.wooden_shovel" => array("Wooden shovel", ""),
    "breakItem.minecraft.wooden_sword" => array("Wooden sword", ""),
);

?>