<?php

$statList = array
(
    "entityKilledBy.Blaze" => array("Blaze", ""),
    "entityKilledBy.CaveSpider" => array("Arraignée bleue", ""),
    "entityKilledBy.Creeper" => array("Creeper", ""),
    "entityKilledBy.Enderman" => array("Enderman", ""),
    "entityKilledBy.Endermite" => array("Endermite", ""),
    "entityKilledBy.Ghast" => array("Ghast", ""),
    "entityKilledBy.Guardian" => array("Gardien", ""),
    "entityKilledBy.LavaSlime" => array("Cube de magma", ""),
    "entityKilledBy.PigZombie" => array("Cochon zombie", ""),
    "entityKilledBy.Shulker" => array("Shulker", ""),
    "entityKilledBy.Silverfish" => array("Poisson d'argent", ""),
    "entityKilledBy.Skeleton" => array("Squelette", ""),
    "entityKilledBy.Slime" => array("Slime", ""),
    "entityKilledBy.Spider" => array("Arraignée", ""),
    "entityKilledBy.Witch" => array("Sorcière", ""),
    "entityKilledBy.Wolf" => array("Loup", ""),
    "entityKilledBy.Zombie" => array("Zombie", ""),
);

?>