<?php

$statList = array
(
    "entityKilledBy.Bat" => array("Chauve-souris", ""),
    "entityKilledBy.Blaze" => array("Blaze", ""),
    "entityKilledBy.CaveSpider" => array("Arraignée bleue", ""),
    "entityKilledBy.Chicken" => array("Poule", ""),
    "entityKilledBy.Cow" => array("Vache", ""),
    "entityKilledBy.Creeper" => array("Creeper", ""),
    "entityKilledBy.Enderman" => array("Enderman", ""),
    "entityKilledBy.Endermite" => array("Endermite", ""),
    "entityKilledBy.EntityHorse" => array("Cheval", ""),
    "entityKilledBy.Ghast" => array("Ghast", ""),
    "entityKilledBy.Guardian" => array("Gardien", ""),
    "entityKilledBy.LavaSlime" => array("Cube de magma", ""),
    "entityKilledBy.MushroomCow" => array("Champimeuh", ""),
    "entityKilledBy.Ozelot" => array("Ocelot", ""),
    "entityKilledBy.Pig" => array("Cochon", ""),
    "entityKilledBy.PigZombie" => array("Cochon zombie", ""),
    "entityKilledBy.Rabbit" => array("Lapin", ""),
    "entityKilledBy.Sheep" => array("Mouton", ""),
    "entityKilledBy.Silverfish" => array("Poisson d'argent", ""),
    "entityKilledBy.Skeleton" => array("Squelette", ""),
    "entityKilledBy.Slime" => array("Slime", ""),
    "entityKilledBy.Spider" => array("Arraignée", ""),
    "entityKilledBy.Squid" => array("Pieuvre", ""),
    "entityKilledBy.Villager" => array("Villageois", ""),
    "entityKilledBy.Witch" => array("Sorcière", ""),
    "entityKilledBy.Wolf" => array("Loup", ""),
    "entityKilledBy.Zombie" => array("Zombie", ""),
);

?>