<?php

$statList = array
(
    "itemEnchanted" => array("Objets enchantés", ""),
    "animalsBred" => array("Animaux élevés", ""),
    "fishCaught" => array("Poissons pêchés", ""),
    "junkFished" => array("Déchets pêchés", ""),
    "treasureFished" => array("Trésors pêchés", ""),
    "talkedToVillager" => array("Interactions avec villageois", ""),
    "tradedWithVillager" => array("Commerces avec villageois", ""),
    "cakeSlicesEaten" => array("Parts de gâteau mangées", ""),
    "cauldronFilled" => array("Chaudrons remplis", ""),
    "cauldronUsed" => array("Chaudrons utilisés", ""),
    "armorCleaned" => array("Armures lavées", ""),
    "bannerCleaned" => array("Bannière lavées", ""),
    "brewingstandInteraction" => array("Interactions avec alambics", ""),
    "beaconInteraction" => array("Interactions avec balises", ""),
    "craftingTableInteraction" => array("Interactions avec établis", ""),
    "furnaceInteraction" => array("Interactions avec fours", ""),
    "dispenserInspected" => array("Interactions avec distributeurs", ""),
    "dropperInspected" => array("Interactions avec droppers", ""),
    "hopperInspected" => array("Interactions avec entonnoirs", ""),
    "chestOpened" => array("Coffres ouverts", ""),
    "trappedChestTriggered" => array("Coffres piégés ouverts", ""),
    "enderchestOpened" => array("Coffres du Néant ouverts", ""),
    "noteblockPlayed" => array("Blocs musicaux joués", ""),
    "noteblockTuned" => array("Blocs musicaux accordés", ""),
    "flowerPotted" => array("Fleurs plantées dans pots", ""),
    "recordPlayed" => array("Disques jouées", ""),
    "sleepInBed" => array("Nuits de sommeil", ""),
);

?>