<?php

$statList = array
(
    "killEntity.Bat" => array("Chauve-souris", ""),
    "killEntity.Blaze" => array("Blaze", ""),
    "killEntity.CaveSpider" => array("Arraignée bleue", ""),
    "killEntity.Chicken" => array("Poule", ""),
    "killEntity.Cow" => array("Vache", ""),
    "killEntity.Creeper" => array("Creeper", ""),
    "killEntity.Enderman" => array("Enderman", ""),
    "killEntity.Endermite" => array("Endermite", ""),
    "killEntity.EntityHorse" => array("Cheval", ""),
    "killEntity.Ghast" => array("Ghast", ""),
    "killEntity.Guardian" => array("Gardien", ""),
    "killEntity.LavaSlime" => array("Cube de magma", ""),
    "killEntity.MushroomCow" => array("Champimeuh", ""),
    "killEntity.Ozelot" => array("Ocelot", ""),
    "killEntity.Pig" => array("Cochon", ""),
    "killEntity.PigZombie" => array("Cochon zombie", ""),
    "killEntity.Rabbit" => array("Lapin", ""),
    "killEntity.Sheep" => array("Mouton", ""),
    "killEntity.Shulker" => array("Shulker", ""),
    "killEntity.Silverfish" => array("Poisson d'argent", ""),
    "killEntity.Skeleton" => array("Squelette", ""),
    "killEntity.Slime" => array("Slime", ""),
    "killEntity.Spider" => array("Arraignée", ""),
    "killEntity.Squid" => array("Pieuvre", ""),
    "killEntity.Villager" => array("Villageois", ""),
    "killEntity.Witch" => array("Sorcière", ""),
    "killEntity.Wolf" => array("Loup", ""),
    "killEntity.Zombie" => array("Zombie", ""),
);

?>