<?php

$defaultKey = "playOneMinute";

$statList = array
(
    "leaveGame" => array("Sessions de jeu", ""),
    "playOneMinute" => array("Temps de jeu", "h"),
    "average" => array("Temps de jeu par jour", "h"),
    "timeSinceDeath" => array("Temps survécu", "h"),
    "sneakTime" => array("Temps accroupi", "h"),
    "jump" => array("Sauts", ""),
    "damageDealt" => array("Dégâts infligés", "♥"),
    "damageTaken" => array("Dégâts subis", "♥"),
    "deaths" => array("Nombre de morts", ""),
    "mobKills" => array("Créatures tués", ""),
    "playerKills" => array("Joueurs tués", ""),
    "drop" => array("Objets lâchés", ""),
);

?>
