<?php

// Titre du serveur
define("TITLE", "Minecrew");

// Le répertoire contenant le serveur Minecraft
define("LOCATION", "server/");

// Lien vers un launcher personnalisé (laisser vide pour aucun)
define("LAUNCHER", "download/launcher.zip");

// Lien vers un dossier de sauvegardes (laisser vide pour aucun)
define("BACKUP", "backups/");

// L'adresse du serveur Minecraft
define("HOSTNAME", "monserveur.com");

// Le port du serveur (par défaut : 25565)
define("PORT", "25565");

?>